sonar.projectKey=video2frames_video-processor
sonar.organization=video2frames


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=video_processor

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=coverage.xml

sonar.python.version=3.14
